[DATALAD RUNCMD] Make tests invoke at least with INFO level so we see what is wrong when it goes awry
Ref: https://github.com/con/duct/issues/320

which is hard to impossible to troubleshoot with all the silence while con-duct tried to convey:

    ERROR    con_duct.suite.plot:plot.py:75 con-duct plot missing required dependency: cannot import name 'backend_registry' from 'matplotlib.backends' (/usr/lib/python3/dist-packages/matplotlib/backends/__init__.py)

=== Do not change lines below ===
{
 "chain": [],
 "cmd": "sed -i -e 's/log_level=\"NONE\"/log_level=\"INFO\"/g' test/test_suite.py",
 "exit": 0,
 "extra_inputs": [],
 "inputs": [],
 "outputs": [],
 "pwd": "."
}
^^^ Do not change lines above ^^^